# 邮件服务配置
server:
  port: 8087

spring:
  application:
    name: alogrithm-mail-service
  config:
    activate:
      on-profile: prod
    import:
      - nacos:common-secret-prod.properties?group=DEFAULT_GROUP&refresh=true
      - nacos:common-web-prod.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-cache-prod.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-rabbitmq-prod.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-mail-prod.yml?group=DEFAULT_GROUP&refresh=true
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:${prod.nacos.addr:localhost:8848}}
        namespace: alogrithm-cloud
        group: DEFAULT_GROUP
        username: ${SPRING_CLOUD_NACOS_USERNAME:${prod.nacos.username:nacos}}
        password: ${SPRING_CLOUD_NACOS_PASSWORD:${prod.nacos.password:nacos}}
      config:
        server-addr: ${SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR:${prod.nacos.addr:localhost:8848}}
        namespace: alogrithm-cloud
        group: DEFAULT_GROUP
        file-extension: yml
        username: ${SPRING_CLOUD_NACOS_USERNAME:${prod.nacos.username:nacos}}
        password: ${SPRING_CLOUD_NACOS_PASSWORD:${prod.nacos.password:nacos}}

