# AI 服务配置
server:
  port: 8089

spring:
  application:
    name: alogrithm-ai-service
  profiles:
    active: default
  config:
    activate:
      on-profile: default
    import:
      - nacos:common-secret.properties?group=DEFAULT_GROUP&refresh=true
      - nacos:common-web.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-cache.yml?group=DEFAULT_GROUP&refresh=true
      - nacos:common-mysql.yml?group=DEFAULT_GROUP&refresh=true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: alogrithm-cloud
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: alogrithm-cloud
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos
  ai:
    dashscope:
      api-key: ${dev.aliyun.dashscope.api-key}
      options:
        model: ${dev.aliyun.dashscope.model-name}

# MyBatis-Plus 业务配置
mybatis-plus:
  type-aliases-package: com.stephen.cloud.ai.model.entity
